/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsUuidGeneratorRouteImport } from './routes/tools/uuid-generator'
import { Route as ToolsTextShareRouteImport } from './routes/tools/text-share'
import { Route as ToolsSecretsGeneratorRouteImport } from './routes/tools/secrets-generator'
import { Route as ToolsPasswordGeneratorRouteImport } from './routes/tools/password-generator'
import { Route as ToolsJsonFormatterRouteImport } from './routes/tools/json-formatter'
import { Route as ToolsHashGeneratorRouteImport } from './routes/tools/hash-generator'
import { Route as ToolsBase64RouteImport } from './routes/tools/base64'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsUuidGeneratorRoute = ToolsUuidGeneratorRouteImport.update({
  id: '/tools/uuid-generator',
  path: '/tools/uuid-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsTextShareRoute = ToolsTextShareRouteImport.update({
  id: '/tools/text-share',
  path: '/tools/text-share',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsSecretsGeneratorRoute = ToolsSecretsGeneratorRouteImport.update({
  id: '/tools/secrets-generator',
  path: '/tools/secrets-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsPasswordGeneratorRoute = ToolsPasswordGeneratorRouteImport.update({
  id: '/tools/password-generator',
  path: '/tools/password-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsJsonFormatterRoute = ToolsJsonFormatterRouteImport.update({
  id: '/tools/json-formatter',
  path: '/tools/json-formatter',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsHashGeneratorRoute = ToolsHashGeneratorRouteImport.update({
  id: '/tools/hash-generator',
  path: '/tools/hash-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsBase64Route = ToolsBase64RouteImport.update({
  id: '/tools/base64',
  path: '/tools/base64',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tools/base64': typeof ToolsBase64Route
  '/tools/hash-generator': typeof ToolsHashGeneratorRoute
  '/tools/json-formatter': typeof ToolsJsonFormatterRoute
  '/tools/password-generator': typeof ToolsPasswordGeneratorRoute
  '/tools/secrets-generator': typeof ToolsSecretsGeneratorRoute
  '/tools/text-share': typeof ToolsTextShareRoute
  '/tools/uuid-generator': typeof ToolsUuidGeneratorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tools/base64': typeof ToolsBase64Route
  '/tools/hash-generator': typeof ToolsHashGeneratorRoute
  '/tools/json-formatter': typeof ToolsJsonFormatterRoute
  '/tools/password-generator': typeof ToolsPasswordGeneratorRoute
  '/tools/secrets-generator': typeof ToolsSecretsGeneratorRoute
  '/tools/text-share': typeof ToolsTextShareRoute
  '/tools/uuid-generator': typeof ToolsUuidGeneratorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tools/base64': typeof ToolsBase64Route
  '/tools/hash-generator': typeof ToolsHashGeneratorRoute
  '/tools/json-formatter': typeof ToolsJsonFormatterRoute
  '/tools/password-generator': typeof ToolsPasswordGeneratorRoute
  '/tools/secrets-generator': typeof ToolsSecretsGeneratorRoute
  '/tools/text-share': typeof ToolsTextShareRoute
  '/tools/uuid-generator': typeof ToolsUuidGeneratorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/tools/base64'
    | '/tools/hash-generator'
    | '/tools/json-formatter'
    | '/tools/password-generator'
    | '/tools/secrets-generator'
    | '/tools/text-share'
    | '/tools/uuid-generator'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/tools/base64'
    | '/tools/hash-generator'
    | '/tools/json-formatter'
    | '/tools/password-generator'
    | '/tools/secrets-generator'
    | '/tools/text-share'
    | '/tools/uuid-generator'
  id:
    | '__root__'
    | '/'
    | '/tools/base64'
    | '/tools/hash-generator'
    | '/tools/json-formatter'
    | '/tools/password-generator'
    | '/tools/secrets-generator'
    | '/tools/text-share'
    | '/tools/uuid-generator'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ToolsBase64Route: typeof ToolsBase64Route
  ToolsHashGeneratorRoute: typeof ToolsHashGeneratorRoute
  ToolsJsonFormatterRoute: typeof ToolsJsonFormatterRoute
  ToolsPasswordGeneratorRoute: typeof ToolsPasswordGeneratorRoute
  ToolsSecretsGeneratorRoute: typeof ToolsSecretsGeneratorRoute
  ToolsTextShareRoute: typeof ToolsTextShareRoute
  ToolsUuidGeneratorRoute: typeof ToolsUuidGeneratorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/uuid-generator': {
      id: '/tools/uuid-generator'
      path: '/tools/uuid-generator'
      fullPath: '/tools/uuid-generator'
      preLoaderRoute: typeof ToolsUuidGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/text-share': {
      id: '/tools/text-share'
      path: '/tools/text-share'
      fullPath: '/tools/text-share'
      preLoaderRoute: typeof ToolsTextShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/secrets-generator': {
      id: '/tools/secrets-generator'
      path: '/tools/secrets-generator'
      fullPath: '/tools/secrets-generator'
      preLoaderRoute: typeof ToolsSecretsGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/password-generator': {
      id: '/tools/password-generator'
      path: '/tools/password-generator'
      fullPath: '/tools/password-generator'
      preLoaderRoute: typeof ToolsPasswordGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/json-formatter': {
      id: '/tools/json-formatter'
      path: '/tools/json-formatter'
      fullPath: '/tools/json-formatter'
      preLoaderRoute: typeof ToolsJsonFormatterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/hash-generator': {
      id: '/tools/hash-generator'
      path: '/tools/hash-generator'
      fullPath: '/tools/hash-generator'
      preLoaderRoute: typeof ToolsHashGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/base64': {
      id: '/tools/base64'
      path: '/tools/base64'
      fullPath: '/tools/base64'
      preLoaderRoute: typeof ToolsBase64RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ToolsBase64Route: ToolsBase64Route,
  ToolsHashGeneratorRoute: ToolsHashGeneratorRoute,
  ToolsJsonFormatterRoute: ToolsJsonFormatterRoute,
  ToolsPasswordGeneratorRoute: ToolsPasswordGeneratorRoute,
  ToolsSecretsGeneratorRoute: ToolsSecretsGeneratorRoute,
  ToolsTextShareRoute: ToolsTextShareRoute,
  ToolsUuidGeneratorRoute: ToolsUuidGeneratorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
